### PR TITLE
feat: Dockerfile.ruby

### PR DESCRIPTION
**Pull request by patrickleet**

### CODE REVIEW

**Comment by patrickleet** [comment]
anything else needed on this?

**Comment by garethjevans** [comment]
@patrickleet we've just merged a change to switch over to skaffold/kaniko (been trying to get this in for ages). Would it be possible to rebase this change and add a skaffold.ruby.yaml in the root directory (use one of the existing files as a template) and we can try and get this in.

**Comment by patrickleet** [comment]
sure, I'll rebase and create a `skaffold.ruby` as well

**Comment by patrickleet** [comment]
@garethjevans done

**Comment by patrickleet** [comment]
I pushed a built ruby image to patrickleet/jenkins-ruby to try it:
https://cloud.docker.com/u/patrickleet/repository/docker/patrickleet/jenkins-ruby

**Comment by patrickleet** [comment]
Created the matching build template as well :)

**Pull request merged**
