### PR TITLE
added java11 maven builder

### PR DESCRIPTION
**Pull request by fabianrindlisbacher**
Added a java 11 maven builder.

### CODE REVIEW

**Comment by jtnord** [comment]
from a quick glance it looked like the old build pods died (but it was a very quick look) - a new build is currently running.

**Comment by fabianrindlisbacher** [comment]
> from a quick glance it looked like the old build pods died (but it was a very quick look) - a new build is currently running.

good. thanks!

**Comment by fabianrindlisbacher** [comment]
How long does it take normally?

**Comment by jtnord** [comment]
lots of errors not sure what is happening here.


```
[ERROR]     mvn deploy:deploy-file -DgroupId=org.abego.treelayout -DartifactId=org.abego.treelayout.core -Dversion=1.0.1 -Dpackaging=hpi -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   org.abego.treelayout:org.abego.treelayout.core:hpi:1.0.1
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   nexus (http://nexus/repository/maven-public/, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Jan 17, 2019 12:08:46 PM io.jenkins.tools.warpackager.lib.util.MavenHelper artifactExists
INFO: Could not download org.abego.treelayout:org.abego.treelayout.core:1.0.1, assuming it is not an HPI and creating /root/.m2/cwp_non_hpi_cache/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayout.core-1.0.1.hpi to remember the assumption.
Jan 17, 2019 12:08:46 PM io.jenkins.tools.warpackager.lib.util.MavenHelper artifactExists
WARNING: Unable to create the /root/.m2/cwp_non_hpi_cache/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayout.core-1.0.1.hpi folder.
Jan 17, 2019 12:08:46 PM io.jenkins.tools.warpackager.lib.config.Config processMavenDep
INFO: Skipping dependency, not an HPI file: org.abego.treelayout:org.abego.treelayout.core:1.0.1
Jan 17, 2019 12:08:46 PM io.jenkins.tools.warpackager.lib.util.MavenHelper artifactExistsInLocalCache
INFO: Checking /root/.m2/repository/org/jenkins-ci/plugins/workflow/workflow-cps/2.61.1/workflow-cps-2.61.1.hpi
Picked up _JAVA_OPTIONS: -Xmx1024m
Jan 17, 2019 12:08:52 PM io.jenkins.tools.warpackager.lib.util.MavenHelper artifactExistsInLocalCache
INFO: Checking /root/.m2/repository/org/jenkins-ci/plugins/script-security/1.50/script-security-1.50.hpi
Picked up _JAVA_OPTIONS: -Xmx1024m
Jan 17, 2019 12:08:58 PM io.jenkins.tools.warpackager.lib.util.MavenHelper artifactExistsInLocalCache
INFO: Checking /root/.m2/repository/io/jenkins/configuration-as-code/1.3/configuration-as-code-1.3.hpi
Picked up _JAVA_OPTIONS: -Xmx1024m
Jan 17, 2019 12:09:06 PM io.jenkins.tools.warpackager.lib.util.MavenHelper artifactExistsInLocalCache
INFO: Checking /root/.m2/repository/io/jenkins-x/client/jx-java-client/1.0.4/jx-java-client-1.0.4.hpi
Picked up _JAVA_OPTIONS: -Xmx1024m
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not find artifact io.jenkins-x.client:jx-java-client:hpi:1.0.4 in nexus (http://nexus/repository/maven-public/)
[ERROR] 
```

**Comment by fabianrindlisbacher** [comment]
not sure either. is the `mvn deploy:deploy-file -DgroupId=org.abego.treelayout -DartifactId=org.abego.treelayout.core -Dversion=1.0.1 -Dpackaging=hpi -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]` executed in your pipeline?

**Comment by fabianrindlisbacher** [comment]
could be a general problem, because the other PR's aren't running through either. or what do you think?

**Comment by fabianrindlisbacher** [comment]
is there an error message?

**Pull request merged**
